export * from './slices/clients'
export * from './slices/products'
export * from './slices/services'
export * from './slices/station'
export * from './slices/tech'
export { default as store } from './store'
